flyway.locations=filesystem:/flyway/migrations
flyway.schemas=flyway_migrations
flyway.outOfOrder=true

# Placeholders for migration scripts
flyway.placeholders.fabric_workspace_id=$(FABRIC_WORKSPACE_ID)
flyway.placeholders.fabric_bronze_lakehouse_id=$(FABRIC_BRONZE_LAKEHOUSE_ID)
flyway.placeholders.fabric_bronze_lakehouse_name=$(FABRIC_BRONZE_LAKEHOUSE_NAME)
flyway.placeholders.fabric_silver_warehouse_name=$(FABRIC_SILVER_WAREHOUSE_NAME)
